### ISSUE TITLE
discover and browse submodules

### ISSUE THREAD

**Issue by antis81** [macgitver/MacGitverModules#5]
Submodules of the active main repository should be shown in a submodule tree.

Sample Tree-Structure:

o Main Repo
o----| Submodule 1
o--------| Submodule 1.1
o--------| Submodule 1.n
o----| Submodule n

This happens in a separate view, to provide ability to easily switch between submodule repositories without loosing focus to the main repo. Further it should have the ability to show/hide the complete tree, to give space for repos without submodules.

**Comment by antis81** [comment]
Note:
When loading a bare repo, in current development state, MacGitver crashes on looking for submodules. That is a special case - libgit2 gives an error on that. We could lookup submodules by parsing the tree of a selected commit (starting from current HEAD). This could show the matching commit of the submodule. It is a bit tricky though and maybe a task for later on development.

**Comment by scunz** [comment]
The Bare-Repo error code was just committed yesterday :-)

Do I understand you correctly, that you want to show a submodule tree for a bare super-project? How is that supposed to work? If the super-project has no working tree, then the most of the submodule we know is: a) it's commit-ish and b) it's URL (But only if we look into HEAD, since it is probably only available in `.gitmodules` and not in `.git/config`).

**Comment by antis81** [comment]
Yes, exactly that :stars:

**Comment by scunz** [comment]
The new RepoTree now _shows_ the submodules. But one cannot do anything with them...

**Comment by scunz** [comment]
With the RepoManager, RepositoryInfo and the associated RepoTreeView, all of this is possible now.
